# Generated by Django 4.1.1 on 2022-09-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
